name: LInux Family Actions #Workflow Name

on: push #Event Name

jobs: #WorkfLow can run one or more Jobs
    linux-ubuntu-actions:
        runs-on: ubuntu-22.04
        steps: #Steps are building blocks of Jobs 
        - name: Welcome To Linux World
          run: echo "Welcome To Linux!"
        
        - name: Verify Current Directory Path
          run: pwd

        - name: Create User  in home Directory
          run: |
            sudo adduser --disabled-password --gecos "" srini
            sudo mkdir -p /home/srini/worspace
            sudo chown srini:srini /home/srini/worspace
            echo User created successfully

        - name: Switch User and run commands
          run: |
            sudo su - srini bash -c '
            who am i
            cd ~/workspace
            echo "File created by $(whoami)" > testfile.txt
            ls -l
            '
        - name: List The Details in Home Directory
          run: |
            sudo su - srini bach -c '
            ls -lrt /home/srini/workspace
            '

        - name: Verify Current Directory Path
          run: cd /home/srini

        - name: Check The Current path
          run: sudo mkdir ~/srini/actions/

        - name: Present Current Directory Path
          run: pwd

