name: LInux Family Actions #Workflow Name

on: push #Event Name

jobs: #WorkfLow can run one or more Jobs
    linux-ubuntu-actions:
        runs-on: ubuntu-22.04
        steps: #Steps are building blocks of Jobs 
        - name: Welcome To Linux World
          run: echo "Welcome To Linux!"
        
        - name: Verify Current Directory Path
          run: pwd

        - name: Create User  in home Directory
          run: sudo adduser srini

        - name: List The Details in Home Directory
          run: ls -d /home/
          
        - name: Verify Current Directory Path
          run: cd /usr/local