name: Linux Family Actions #Workflow Name

on: push #Event Name

jobs: #WorkfLow can run one or more Jobs
    linux-ubuntu-actions:
        runs-on: ubuntu-22.04
        steps: #Steps are building blocks of Jobs 
        - name: Welcome To Linux World
          run: echo "Welcome To Linux!"
        
        - name: Verify Current Directory Path
          run: pwd

        - name: Create User  in home Directory
          run: |
            sudo adduser --disabled-password --gecos "" srini
            sudo mkdir -p /home/srini/workspace
            sudo chown srini:srini /home/srini/workspace
            echo User created successfully

        - name: Switch User and run commands
          run: |
            sudo su - srini bash -c '
            who am i
            cd ~/workspace
            echo "File created by $(whoami)" > testfile.txt
            ls -l
            pwd
            cat testfile.txt
            pwd
            history > history.txt
            cat history.txt
            '
        - name: List The Details in Home Directory
          run: |
            sudo su - srini bach -c '
            cd ~/workspace
            ls -lrt
            echo $history
            cat history.txt           '

        - name: Present Current Directory Path
          run: pwd

        - name: Creating dummy files in Newly Created Path
          run: |
            sudo su - srini bash -c 'for i in {1..10}; do touch "/home/srini/file_$(date +%M)_$i.txt"; done'
            echo "The below files creating..... "
            sudo ls -ltr /home/srini/workspace
            echo `cat /home/srini/workspace/testfile.txt`
            echo "Files Created Successfully"

