name: multiple-Jobs
on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Install cowsay Program
              run: sudo apt install cowsay -y
              
            - name: Execute CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON" >> dragon.txt

            - name: Sleep for 30 seconds
              run: sleep 30

    test_job_2:
      needs: build_job_1
        runs-on: ubuntu-latest
        steps:
          - name: Sleep for 10 seconds
            run: sleep 10

          - name: Test Files Exists
            run: grep -i "dragon" dragon.txt
    deploy_job_3:
      needs: [test_job_2]
        runs-on: ubuntu-latest
        steps:
          - name: Read Files
            run: cat dragon.txt

          - name: Deploy
            run: echo "Deploy... .. .. .. "

