name: Step level Env Variables and Secrets
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log Level (info, debug, error, critical, urgent)'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - warn
          - error
          - debug
          - fatal/critical
      Environment:
        description: 'Environemnt To Deploy the Request '
        required: true
        default: Productions
        type: choice
        options:
          - Development
          - Testing
          - Qa
          - PNV
          - Staging
          - Integration
          - UAT
          - Demo
          - Productions
      version_tag:
        description: "Tag to deploy as part of deployment"
        required: true
      helm_repo_config_branch:
        description: "This field is used for pass helm repo branch as part of deployment"
        required: true
      namesapce_name:
        description: "This branch is used to pass namespace name where we are dploying the workload"
        required: true
      artifactory_path:
        description: "Artifactory path to where image resides"
        required: true
      
      
        
      





# Environment Variables values hardcoded in steps
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: srinivas
                IMAGE_NAME: github-action-nginx
              run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/${{ env.IMAGE_NAME }}:latest

            - name: Docker Login
              env:
                DOCKER_USERNAME: srinivas
                DOCKER_PASSWORD: securepassword
              run: echo docker login --username=$DOCKER_USERNAME --password=${{ env.DOCKER_PASSWORD }}

            - name: Docker Publish
              env:               
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: srinivas
                IMAGE_NAME: github-action-nginx
              run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
          - name: Docker Run
            env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: srinivas
                IMAGE_NAME: github-action-nginx
            run: |
              echo docker run -d -p 8080:8080 ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest
              sleep 300
