name: Exploring Variables and Secrets

on: 
    push

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: docker build -t docker.io/8754812746/github-actions-nginx:latest

            - name: Docker Login
              run: docker login --username=8754812746 --password=@dnokm@lleB9

            - name: Docker Publish
              run: docker push docker.io/8754812746/github-actions-nginx:latest
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
          - name: Docker Run
            run: docker run -d -p 8080:8080 docker.io/8754812746/github-actions-nginx:latest