name: Workflow Fileters And Activities
on:
    workflow_dispatch:  
    push: 
        branches:
            - main
            - '!feature/*'
    #brnaches_ignore: 
    
    pull_request:
        types:
            - opened 
            - closed
        paths-ignore: 
            - README.MD
        branches: 
            - main


jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
          - name: Capturing Which Event is Trigerring
            run: echo Capturing Which Event is Trigerring - ${{ github.event_name }}
  